# Generated by Django 2.2.4 on 2020-04-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact us Records'},
        ),
        migrations.CreateModel(
            name='CFIProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='CFIProject_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Category')),
            ],
            options={
                'verbose_name_plural': 'CFI Projects',
            },
        ),
    ]
