# Generated by Django 2.2.4 on 2021-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200412_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFITeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='CFITeam_images')),
                ('facebook', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('linkedin', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('twitter', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('github', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('batch', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
