# Generated by Django 2.2.4 on 2021-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_cfiteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='CFIEvents')),
                ('about', models.CharField(max_length=512)),
            ],
        ),
    ]
